---
title: "AGoldberg_Assign10"
author: "Andrew Goldberg"
date: "November 30, 2016"
output: html_document
---

#rstudio crashed and I lost my work, so I have to rewrite my solutions here, but lost some of my experimentation...
```{r}
#Form the A matrix. Then, introduce decay and form the B matrix as we did in the course notes.
A <- matrix(c(0,0,1/3,0,0,0,1/2,0,1/3,0,0,0,1/2,0,0,0,0,0,0,0,0,0,1/2,1,0,0,1/3,1/2,0,0,0,0,0,1/2, 1/2,0),ncol = 6)

#Then, introduce decay and form the B matrix as we did in the course notes.
decay <- matrix(1L, nrow = n, ncol = n)
n=6
B <- .85*A+(.15*(decay/n))

```

```{r}
#Start with a uniform rank vector r and perform power iterations on B till convergence.
r <- c(.167,.167, .167, .167, .167, .167)

#imitating notes, A*r does not equal the results promised
A%*%r
#but transpose(A)*r does (will not for future)
t(A)%*%r

convergence <- function(B, r, n){
  i <- n
  Br <- (B%*%r)
    while(i>1){
      Br <- B%*%Br
      i = i -1
  }
  print(Br)
}
convergence(B, r, 100)

#data just decays further with higher iterations

#looking at the data, one of the nodes doesn't add to 1
rowSums(B)

#thankfully Joy posted a Cornell lecture, suggesting to substitute the bad node for an equally distributed vector
B[2,] <- rep(1/n, each=n)

#try convergence again
convergence(B,r,100)

#now I remembered that the A originally needed to be transposed, so the B does as well...
convergence(t(B), r, 10000)
```

```{r}
#Compute the eigen-decomposition of B and verify that you indeed get an eigenvalue of 1 as the largest eigenvalue and that its corresponding eigenvector is the same vector that you obtained in the previous power iteration method. Further, this eigenvector has all positive entries and it sums to 1.

eigen(t(B))

```

```{r}
library(igraph)
#unnecessary but fun to play with:
g1 <- graph.formula( 1 +-+ 3 --+ 2 +-- 1, 3 --+ 5 --+ 6 +-+ 4 +-+ 5)
gorder(g1)
#Use the graph package in R and its page.rank method to compute the Page Rank of the graph as given in A.

pagerankvector <- page_rank(g1)$vector
pagerankvector[order(as.integer(names(pagerankvector)))]

#unnecessary but fun to play with:
plot(g1)
```



