---
title: "HW1b AGOLDBERG"
author: "Andrew Goldberg"
date: "October 27, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
v1 <- c(1,1,3)
v2 <- c(2,-1,5)
v3 <- c(-1,-2,4)
b <- c(1,2,6)

A <- rbind(v1,v2,v3)
AB <- cbind(A, b)
Ab <- cbind(A, b)

#double check (if first and second row = 0, can flip and skip process for that row)
if (Ab[1,][1] == 0){
  Ab[c(1,2),] <- Ab[c(2,1),]
    if (Ab[1,][1] == 1){
      Ab[c(1,3),] <- Ab[c(1,2)]
    }
}

#elimination
mult1 <- (Ab[2,][1])/(Ab[1,][1])
Ab[2,] <- Ab[2,] - (mult1*Ab[1,])
mult2 <- (Ab[3,][1])/(Ab[1,][1])
Ab[3,] <- Ab[3,] - (mult2*Ab[1,])

if (Ab[2,][2] == 0){
  Ab[c(2,3),] <- Ab[c(3,2),]
}

mult12 <- (Ab[3,][2])/(Ab[2,][2])
Ab[3,] <- Ab[3,] - (mult12*Ab[2,])

x3 <- Ab[3,][4]/Ab[3,][3]
x2 <- (Ab[2,][4]-(x3*Ab[2,][3]))/Ab[2,][2]
x1 <- (Ab[1,][4]-(x3*Ab[1,][3])-(x2*Ab[1,][2]))

solution <- c(x1, x2, x3)
setNames(solution, c("x1", "x2", "x3"))

```

