---
title: "AGoldberg_Assign3"
author: "Andrew Goldberg"
date: "November 14, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Q1}
#What is the rank of the matrix A?
A1 <- matrix(c(1,-1,0,5,2,0,1,4,3,1,-2,-2,4,3,1,-3), nrow=4)
LUdecomp <- function(OMatrix) {
  size <- length(OMatrix[,1])
  elimatrix <- matrix(0, size, size)
  
  for(i in 1:size){
    elimatrix[i,i] <- 1
  }

  for(i in head(1:nrow(OMatrix),-1)){
    for(j in head(i:nrow(OMatrix),-1)){
      multiplier <- (OMatrix[(j+1),][i])/(OMatrix[i,][i])
      elimatrix[(j+1),i] <- multiplier
      OMatrix[(j+1),] <- OMatrix[(j+1),] - (multiplier*OMatrix[i,])
      
      }  
    }
    print(OMatrix)
}
A1elim <- LUdecomp(A1)
#this is an invertible matrix, with full rank of 4
```


```{r q2}
#(2) Given an mxn matrix where m > n, what can be the maximum rank? The mini-
#mum rank, assuming that the matrix is non-zero?

#the maximum rank would be n.
#the minimum rank would be 1, if all rows are dependent
```

```{r q3}
#What is the rank of matrix B?
B3 <- matrix(c(1,3,2,2,6,4,1,3,2), nrow=3)
#using my LU algorithm, it shows a rank of one with the 2nd and 3rd row dependent on the first. Just looking at it, row 1 = 2x row2 and 3x row3, so all identical. 
LUdecomp(B3)
```

```{r Problem set 2}
#Compute the eigenvalues and eigenvectors of the matrix A. You'll need to show your
#work. You'll need to write out the characteristic polynomial and show your solution.

A4 <- matrix(c(1,0,0,2,4,0,3,5,6), nrow=3)

#Need to solve:
#___________(   [lambda, 0, 0])
#determinant(A4-[0, lambda, 0]) = 0
#___________(   [0, 0, lambda])

#which turns into
#__________([1-lambda, 2, 3])
#determiant([0, 4-lambda, 5]) = 0
#__________([0, 0, 6-lambda])

#which reduces to:
#(1-lambda)(4-lambda)(6-lambda)

#if we were to multiply it out to get the characteristic polynomial:
#=(4-L-4L+L^2)(6-L)
#=(4-5L+L^2)(6-L)
#=24-30L+6L^2-4L+5L^2-L^3
#=24-34L+1L^2-L^3

#Now we have 3 eiganvalues:
#Lambda = 1, Lambda = 4, Lambda = 6

#plugging in Lambda = 1
Lambda1 <- matrix(c(0,0,0,2,3,0,3,5,5), nrow=3)
#which turns into
#([0, 2, 3])[v1]
#([0, 3, 5])[v2]= 0
#([0, 0, 5])[v3]

#set v1=t since row 1 is all 0's
#since 5v3=0 AND 3v2+5v3=0, both v2 and v3 = 0
#so eigenvector at lambda = 1 is:
eigenlambda1 <- c(1,0,0)

#plugging in Lambda = 4
Lambda4 <- matrix(c(-3,0,0,2,0,0,3,5,2),nrow=3)
#which turns into
#([-3, 2, 3])[v1]
#([0, 0, 5]) [v2]= 0
#([0, 0, 2]) [v3]

#set v3 = 0 to cancel out third column
#then set either v1 or v2 to t
#if v1 = t:
#-3t + 2v2 = 0
#v2 = 3/2t
eigenlambda4 <- c(1,3/2,0)

#plugging in Lambda = 6
Lambda6 <- matrix(c(-5,0,0,2,02,0,3,5,0))
#which turns into
#([-5, 2, 3]) [v1]
#([0, -2, 5]) [v2]= 0
#([0, 0, 0])  [v3]

#set v3 = t
#-2v2 + 5t = 0
#v2 = 5/2t
#then -5v1 + 5t + 3t = 0
#v1 = 8/5t
eigenlambda6 <- c(8/5,5/2,1)
```

```{r calculate unit eigenvectors}
#unit vector function
scalar1 <- function(x) {x / sqrt(sum(x^2))}

#unit vector at lambda = 1
scalar1(eigenlambda1)

#unit vector at lambda = 4
scalar1(eigenlambda4)

#unit vector at lambda = 6
scalar1(eigenlambda6)
```