---
title: "Homework 5"
author: "Andrew Goldberg"
date: "November 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r PS1}
A <- matrix(c(1,1,1,1,0,1,3,4), nrow=4)
b <- c(0,8,8,20)

#Write R markdown script to compute ATA and ATb.
AtA <- t(A)%*%A
AtA
Atb <- t(A)%*%b
Atb

#Solve for x hat in R using the above two computed matrices.
xHat <- solve(AtA)%*%Atb
xHat

#What is the squared error of this solution?
squaredError <- sum((b-(A%*%xHat))^2)
squaredError

#Instead of b = [0; 8; 8; 20], start with p = [1; 5; 13; 17] and find the exact solution (i.e. show that this system is solvable as all equations are consistent with each other. This should result in an error vector e = 0).

p <- c(1,5,13,17)
Atp <- t(A)%*%p
xHat1 <- solve(AtA)%*%Atp
p1 <- A%*%xHat1

isTRUE(all.equal(as.vector(p), as.vector(p1)))

error <- p1 - p
error

#Show that the error e = b - p = [-1,3,-5,3]
p2 <- A%*%xHat
e <- b - p2
e

#Show that the error e is orthogonal to p and to each of the columns of A.

#orthogonal means their dot products should equal zero (or close approximations):
p%*%e
A[,1]%*%e
A[,2]%*%e
```

```{r PS2}
#Write an R markdown script that takes in the auto-mpg data, extracts an A matrix from the first 4 columns and b vector from the fifth (mpg) column.

setwd("C:\\Users\\andrew\\Desktop\\Computational Math\\Week 5\\assign5 (2)\\assign5")
df <- read.table("auto-mpg.data", header = FALSE)
A2 <- data.matrix(df[,(c(1:4))])
b2 <- df[,5]

#Using the least squares approach, your code should compute the best fitting solution. That is, find the best fitting equation that expresses mpg in terms of the other 4 variables.

AtA2 <- t(A2)%*%A2
Atb2 <- t(A2)%*%b2
xHat2 <- solve(AtA2)%*%Atb2
p2 <- A2%*%xHat2
lsfit(A2, b2)
#Finally, calculate the fitting error between the predicted mpg of your model and the actual mpg.
error2 <- b2 - p2

```